apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 2
    requireLogin: true
    persistenceEnabled: true
    journalType: nio
    messageMigration: true
    storage:
      size: 1Gi
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "2Gi"
  console:
    expose: true
  acceptors:
    - name: core
      port: 61616
      protocols: core
    - name: core-tls
      port: 61617
      protocols: core
      expose: true
      sslEnabled: true
      sslSecret: artemis-broker-tls-secret
    - name: amqp
      port: 5672
      protocols: amqp
    - name: amqp-tls
      port: 5673
      protocols: amqp
      expose: true
      sslEnabled: true
      sslSecret: artemis-broker-tls-secret
  addressSettings:
    applyRule: merge_all
    addressSetting:
      - match: "#"
        redistributionDelay: 5000
  brokerProperties:
    - "globalMaxSize=1GiB"
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=OFF_WITH_REDISTRIBUTION"
    - "AMQPConnections.dc2-to-dc1.uri=tcp://${DC1_HOST}:${DC1_PORT}?transport.trustStoreLocation=/etc/artemis-broker-tls-secret-volume/client.ts&transport.trustStorePassword=password"
    - "AMQPConnections.dc2-to-dc1.user=${DC1_USER}"
    - "AMQPConnections.dc2-to-dc1.password=${DC1_PASS}"
    - "AMQPConnections.dc2-to-dc1.connectionElements.mirror.type=MIRROR"
    - "AMQPConnections.dc2-to-dc1.connectionElements.mirror.addressFilter=app.foo"
    - "AMQPConnections.dc2-to-dc1.connectionElements.mirror.messageAcknowledgments=true"
    - "AMQPConnections.dc2-to-dc1.connectionElements.mirror.queueRemoval=true"
    - "AMQPConnections.dc2-to-dc1.connectionElements.mirror.queueCreation=true"
